name: build and test
run-name: ${{ github.actor }} build and tests qulisp
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./ci/build_and_test.sh
